// Code generated by mockery v2.53.5. DO NOT EDIT.

package ocr

import mock "github.com/stretchr/testify/mock"

// MockResizer is an autogenerated mock type for the Resizer type
type MockResizer struct {
	mock.Mock
}

type MockResizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResizer) EXPECT() *MockResizer_Expecter {
	return &MockResizer_Expecter{mock: &_m.Mock}
}

// ResizeImage provides a mock function with given fields: imageData, maxDimension
func (_m *MockResizer) ResizeImage(imageData []byte, maxDimension int) ([]byte, error) {
	ret := _m.Called(imageData, maxDimension)

	if len(ret) == 0 {
		panic("no return value specified for ResizeImage")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, int) ([]byte, error)); ok {
		return rf(imageData, maxDimension)
	}
	if rf, ok := ret.Get(0).(func([]byte, int) []byte); ok {
		r0 = rf(imageData, maxDimension)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, int) error); ok {
		r1 = rf(imageData, maxDimension)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResizer_ResizeImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResizeImage'
type MockResizer_ResizeImage_Call struct {
	*mock.Call
}

// ResizeImage is a helper method to define mock.On call
//   - imageData []byte
//   - maxDimension int
func (_e *MockResizer_Expecter) ResizeImage(imageData interface{}, maxDimension interface{}) *MockResizer_ResizeImage_Call {
	return &MockResizer_ResizeImage_Call{Call: _e.mock.On("ResizeImage", imageData, maxDimension)}
}

func (_c *MockResizer_ResizeImage_Call) Run(run func(imageData []byte, maxDimension int)) *MockResizer_ResizeImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(int))
	})
	return _c
}

func (_c *MockResizer_ResizeImage_Call) Return(_a0 []byte, _a1 error) *MockResizer_ResizeImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResizer_ResizeImage_Call) RunAndReturn(run func([]byte, int) ([]byte, error)) *MockResizer_ResizeImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResizer creates a new instance of MockResizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResizer {
	mock := &MockResizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
