// Code generated by mockery v2.53.5. DO NOT EDIT.

package ocr

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOCRClient is an autogenerated mock type for the OCRClient type
type MockOCRClient struct {
	mock.Mock
}

type MockOCRClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOCRClient) EXPECT() *MockOCRClient_Expecter {
	return &MockOCRClient_Expecter{mock: &_m.Mock}
}

// OCRImage provides a mock function with given fields: ctx, imageData
func (_m *MockOCRClient) OCRImage(ctx context.Context, imageData []byte) (string, float64, int, error) {
	ret := _m.Called(ctx, imageData)

	if len(ret) == 0 {
		panic("no return value specified for OCRImage")
	}

	var r0 string
	var r1 float64
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (string, float64, int, error)); ok {
		return rf(ctx, imageData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) string); ok {
		r0 = rf(ctx, imageData)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) float64); ok {
		r1 = rf(ctx, imageData)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, []byte) int); ok {
		r2 = rf(ctx, imageData)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, []byte) error); ok {
		r3 = rf(ctx, imageData)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockOCRClient_OCRImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OCRImage'
type MockOCRClient_OCRImage_Call struct {
	*mock.Call
}

// OCRImage is a helper method to define mock.On call
//   - ctx context.Context
//   - imageData []byte
func (_e *MockOCRClient_Expecter) OCRImage(ctx interface{}, imageData interface{}) *MockOCRClient_OCRImage_Call {
	return &MockOCRClient_OCRImage_Call{Call: _e.mock.On("OCRImage", ctx, imageData)}
}

func (_c *MockOCRClient_OCRImage_Call) Run(run func(ctx context.Context, imageData []byte)) *MockOCRClient_OCRImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockOCRClient_OCRImage_Call) Return(text string, cost float64, attempts int, err error) *MockOCRClient_OCRImage_Call {
	_c.Call.Return(text, cost, attempts, err)
	return _c
}

func (_c *MockOCRClient_OCRImage_Call) RunAndReturn(run func(context.Context, []byte) (string, float64, int, error)) *MockOCRClient_OCRImage_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAPIKey provides a mock function with given fields: ctx
func (_m *MockOCRClient) ValidateAPIKey(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAPIKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOCRClient_ValidateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAPIKey'
type MockOCRClient_ValidateAPIKey_Call struct {
	*mock.Call
}

// ValidateAPIKey is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOCRClient_Expecter) ValidateAPIKey(ctx interface{}) *MockOCRClient_ValidateAPIKey_Call {
	return &MockOCRClient_ValidateAPIKey_Call{Call: _e.mock.On("ValidateAPIKey", ctx)}
}

func (_c *MockOCRClient_ValidateAPIKey_Call) Run(run func(ctx context.Context)) *MockOCRClient_ValidateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOCRClient_ValidateAPIKey_Call) Return(_a0 error) *MockOCRClient_ValidateAPIKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOCRClient_ValidateAPIKey_Call) RunAndReturn(run func(context.Context) error) *MockOCRClient_ValidateAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOCRClient creates a new instance of MockOCRClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOCRClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOCRClient {
	mock := &MockOCRClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
