// Code generated by mockery v2.53.5. DO NOT EDIT.

package ocr

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetImageNames provides a mock function with given fields: dir
func (_m *MockRepository) GetImageNames(dir string) ([]string, error) {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for GetImageNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(dir)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetImageNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageNames'
type MockRepository_GetImageNames_Call struct {
	*mock.Call
}

// GetImageNames is a helper method to define mock.On call
//   - dir string
func (_e *MockRepository_Expecter) GetImageNames(dir interface{}) *MockRepository_GetImageNames_Call {
	return &MockRepository_GetImageNames_Call{Call: _e.mock.On("GetImageNames", dir)}
}

func (_c *MockRepository_GetImageNames_Call) Run(run func(dir string)) *MockRepository_GetImageNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRepository_GetImageNames_Call) Return(_a0 []string, _a1 error) *MockRepository_GetImageNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetImageNames_Call) RunAndReturn(run func(string) ([]string, error)) *MockRepository_GetImageNames_Call {
	_c.Call.Return(run)
	return _c
}

// LoadImageByName provides a mock function with given fields: dir, filename
func (_m *MockRepository) LoadImageByName(dir string, filename string) ([]byte, error) {
	ret := _m.Called(dir, filename)

	if len(ret) == 0 {
		panic("no return value specified for LoadImageByName")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return rf(dir, filename)
	}
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(dir, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(dir, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_LoadImageByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadImageByName'
type MockRepository_LoadImageByName_Call struct {
	*mock.Call
}

// LoadImageByName is a helper method to define mock.On call
//   - dir string
//   - filename string
func (_e *MockRepository_Expecter) LoadImageByName(dir interface{}, filename interface{}) *MockRepository_LoadImageByName_Call {
	return &MockRepository_LoadImageByName_Call{Call: _e.mock.On("LoadImageByName", dir, filename)}
}

func (_c *MockRepository_LoadImageByName_Call) Run(run func(dir string, filename string)) *MockRepository_LoadImageByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_LoadImageByName_Call) Return(_a0 []byte, _a1 error) *MockRepository_LoadImageByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_LoadImageByName_Call) RunAndReturn(run func(string, string) ([]byte, error)) *MockRepository_LoadImageByName_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOutput provides a mock function with given fields: path, content
func (_m *MockRepository) SaveOutput(path string, content string) error {
	ret := _m.Called(path, content)

	if len(ret) == 0 {
		panic("no return value specified for SaveOutput")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(path, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SaveOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOutput'
type MockRepository_SaveOutput_Call struct {
	*mock.Call
}

// SaveOutput is a helper method to define mock.On call
//   - path string
//   - content string
func (_e *MockRepository_Expecter) SaveOutput(path interface{}, content interface{}) *MockRepository_SaveOutput_Call {
	return &MockRepository_SaveOutput_Call{Call: _e.mock.On("SaveOutput", path, content)}
}

func (_c *MockRepository_SaveOutput_Call) Run(run func(path string, content string)) *MockRepository_SaveOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_SaveOutput_Call) Return(_a0 error) *MockRepository_SaveOutput_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SaveOutput_Call) RunAndReturn(run func(string, string) error) *MockRepository_SaveOutput_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
